# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
## main branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: main
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major bumps in main, as it breaks the group bump process
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## main branch config ends here

## release-30.0 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: release-30.0
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## release-30.0 branch config ends here

## release-29.0 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: release-29.0
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## release-29.0 branch config ends here

## release-28.0 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: release-28.0
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## release-28.0 branch config ends here

## release-27.0 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: release-27.0
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## release-27.0 branch config ends here
