name: build-images-action

permissions:
  contents: read

on:
  push:
    branches:
    - 'main'
    - 'release-*'
    tags:
    - 'v*'

jobs:
  build_ironic:
    name: Build Ironic container image
    if: github.repository == 'metal3-io/ironic-image'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'ironic'
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build_sushy-tools:
    name: Build sushy-tools image
    if: github.repository == 'metal3-io/ironic-image'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'sushy-tools'
      dockerfile-directory: resources/sushy-tools
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build_vbmc:
    name: build vbmc image
    if: github.repository == 'metal3-io/ironic-image'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'vbmc'
      dockerfile-directory: resources/vbmc
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build_client:
    name: build ironic-client image
    if: github.repository == 'metal3-io/ironic-image'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'ironic-client'
      dockerfile-directory: resources/ironic-client
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
